spring:
  # 1. 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/my_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: '314500'
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. 邮件配置 (注意：mail 必须和 datasource 对齐)
  mail:
    host: smtp.qq.com
    port: 465
    username: 3497136392@qq.com
    password: irovuhweodjmcjbj
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000

# 3. 其他配置
server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
